---
title: "data-prep"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data-prep}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  eval = FALSE,
  comment = "#>"
)
```

```{r setup}
library(FPSpatioTemp)
```


talk about stratification

#### Missing

* for any site not surveyed or observed, the response variable should be `NA` (not `0`, `-999`, or any other missing value convention). The variable type should be `<dbl>` or `<int>`.

For example,

```{r}
summary(moose_complete$totalmoosena)
```

```{r}
moose_complete <- moose_complete |>
  mutate(predweights_22 = if_else(Surveyyear == 2022 & samp_frame == 1,
                                  true = 1, 
                                  false = 0)) 
```

## example with 2022 data

```{r}

moose_prep <- moose_complete |>
## use most recent stratification
  mutate(newstrat = if_else(Surveyyear == 2022,
                            true = stratfact, 
                            false = NA_integer_)) |>
  dplyr::group_by(ID) |> fill(newstrat, .direction = "updown") |>
  ungroup()

## only use data from sites within 2022's sampling frame

moose_df_merge <- moose_prep |>
  filter(predweights_22 == 1) |> select(ID)
moose_final_all <- semi_join(moose_prep, moose_df_merge)

moose_final_all |> filter(Surveyyear >= 2014) |>
  group_by(stratfact) |>
  summarise(n())
  ##summarise(sum(!is.na(totalmoosena)))
## 2018 has a very large outlier, driving up the
## variability in the predictor
## newstrat uses the stratum from 2022
mod_22 <- stlmfit(formula = totalmoosena ~ stratfact,
                  data = moose_final_all |> filter(Surveyyear >= 2016),
                  xcoord = "xcoords",
                  ycoord = "ycoords",
                  tcoord = "Surveyyear")

pred_obj_all <- predict(object = mod_22, wtscol = "predweights_22")
pred_obj_all$totalpred
pred_obj_all$predvar |> sqrt()

library(sptotal)
moose_22_sptotal <- moose_18_22 |>
  filter(predweights_22 == 1) 
mod_sptot <- slmfit(totalmoosena ~ newstrat,
                  data = moose_22_sptotal,
                  xcoord = "xcoords",
                  ycoord = "ycoords")
pred_sptot <- predict(mod_sptot)
pred_sptot$FPBK_Prediction
pred_sptot$PredVar |> sqrt()
```



