---
title: "Spatiotemporal Abundance Prediction"
header-includes:
   - \usepackage{bm} 
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Reference: <http://faculty.missouri.edu/~wiklec/ST_3_wikle_Boston_Descriptive.pdf> -->

## Motivation

Moose surveys in Alaska and western Canada are often performed annually in many regions. The primary goal of these surveys is to predict moose abundance, the total number of moose, in the region. Because of time and money constraints, only some areas (sites) in the region of interest are selected to be in the survey. Biologists fly to these selected sites, count the number of moose, and use a spatial statistical model to find a prediction for the total abundance.

Though these surveys are annual, each survey is analysed completely independently of surveys from previous years. For example, a survey conducted in the year 2019 only uses counts on sites that were sampled in that year. All data from previous years is ignored by the model.

However, using counts from previous years in a model that incorporates both spatial and temporal correlation (spatiotemporal) could result in a prediction that is more precise than predictions from a spatial model using only counts from the most recent survey year. 

Though the framework of the motivation is given with an example on moose surveys, this type of analysis could be useful for many examples involving prediction in a finite region with sites that are surveyed annually.

## Model Development

The development of the following model combines standard spatiotemporal kriging with finite population block kriging. 

#### Spatiotemporal Model

Let $Y(\mathbf{s}_{i}, \mathbf{t}_j)$, $i = 1, 2, \ldots, n_{sp}$ and $j = 1, 2, \ldots, n_{t}$ be a latent, unobserved spatiotemporal surface with $n_{sp}$ as the number of spatial sites and $n_t$ as the number of time points. With each spatial location at each time point, the total number of data points (observed and unobserved) is $n_{sp}n_{t} \equiv N$. The underlying spatiotemporal surface is

\begin{equation}
\mathbf{y}(\mathbf{s}_{i}, \mathbf{t}_j) = \mathbf{X} \bm{\beta} + \bm{\epsilon}(\mathbf{s}_{i}, \mathbf{t}_j),
\end{equation}

where $\mathbf{y}$ is a vector of the response indexed at the $i^{th}$ spatial location $\mathbf{s}_{i}$ and $j^{th}$ time point $\mathbf{t}_j$, $\mathbf{X}$ is a design matrix for fixed effects, and $\bm{\beta}$ is a parameter vector of fixed effects. 

The error $\bm{\epsilon}(\mathbf{s}_{i}, \mathbf{t}_j)$ can be decomposed into spatial and temporal components, as in Dumelle et al. (2021). In particular, a sum-with-error linear mixed model for response vector $\mathbf{y}(\mathbf{s}_{i}, \mathbf{t}_j)$ is

\begin{equation}
\mathbf{y}(\mathbf{s}_{i}, \mathbf{t}_j) = \mathbf{X} \bm{\beta} + \mathbf{Z}_{sp} \bm{\delta} + \mathbf{Z}_{sp} \bm{\gamma} + \mathbf{Z}_t \bm{\tau} + \mathbf{Z}_t \bm{\eta} + \bm{\nu}.
\end{equation}

$\mathbf{Z}_{sp}$ is an $N \times n_{sp}$ matrix where the values in a general row $k$ in $\mathbf{Z}_{sp}$ at location $\mathbf{s}_{i}$ are a $1$ in the $i^{th}$ column and 0's in all other columns. Similarly, $\mathbf{Z}_t$ is an $N \times n_{t}$ matrix where the values in a general row $k$ in $\mathbf{Z}_t$ at time point $\mathbf{t}_j$ are a $1$ in the $j^{th}$ column and 0's in all other columns. We assume that $\bm{\delta}$, $\bm{\gamma}$, $\bm{\tau}$, $\bm{eta}$, and $\bm{\nu}$ all are all mean $\mathbf{0}$ vectors of length $n_{sp}$, $n_{sp}$, $n_t$, $n_t$, and $N$, respectively, with the covariances

\begin{align*}
cov(\bm{\delta}) &= \sigma^2_{\delta} \mathbf{R}_{sp} \\
cov(\bm{\gamma}) &= \sigma^2_{\gamma} \mathbf{I}_{sp} \\
cov(\bm{\tau}) &= \sigma^2_{\tau} \mathbf{R}_t \\
cov(\bm{\eta}) &= \sigma^2_{\eta} \mathbf{I}_t \\
cov(\bm{\nu}) &= \sigma^2_{\nu} \mathbf{I}_N,
\end{align*}

where $\mathbf{R}_{sp}$ is a spatial correlation matrix and $\mathbf{R}_t$ is a temporal correlation matrix. $\sigma^2_{\delta}$ and $\sigma^2_{\gamma}$ are the spatial partial sill and spatial nugget, $\sigma^2_{\tau}$ and $\sigma^2_{\eta}$ are the temporal partial sill and temporal nugget, and $\sigma^2_{\nu}$ is spatiotemporal independent error variance parameter.

If we assume that $\bm{\delta}$, $\bm{\gamma}$, $\bm{\tau}$, $\bm{\eta}$, and $\bm{\nu}$ are mutually independent of each other, then 

\begin{equation}
var(\mathbf{y}) \equiv \bm{\Sigma} = \sigma^2_{\delta} \mathbf{Z}_{sp} \mathbf{R}_{sp} \mathbf{Z}_{sp}' + \sigma^2_{\gamma} \mathbf{Z}_{sp} \mathbf{I}_{sp} \mathbf{Z}_{sp}' + \sigma^2_{\tau} \mathbf{Z}_t \mathbf{R}_t \mathbf{Z}_t'+ \sigma^2_{\eta} \mathbf{Z}_t \mathbf{I}_t \mathbf{Z}_t' + \sigma^2_{\nu} \mathbf{I}_N.
\end{equation}

A common form of $\mathbf{R}_{sp}$ is exponential. For observations at locations $i$ and $i'$ at $h_{ii'}$ distance apart,

\begin{equation}
\mathbf{R}_{sp, ii'} = \text{exp}(-h_{ii'} / \phi),
\end{equation}

where $\phi$ is the range parameter.

A common form of $\mathbf{R}_t$ is also exponential, or, AR(1). For observations at time points $j$ and $j'$ that are $m_{jj'}$ units apart,

\begin{equation}
\mathbf{R}_{t, jj'} = \text{exp}(-m_{jj'} / \rho),
\end{equation}

where $\rho$ is the autocorrelation parameter.

If we assume that $\mathbf{y}$ is multivariate normal with mean $\mathbf{X} \bm{\beta} \equiv \bm{\mu}$ and variance $\bm{\Sigma}$, then all parameters can be estimated with Maximum Likelihood or Restricted Maximum Likelihood.

#### Finite Population Block Kriging

The above model for $\mathbf{Y}$ is a model for $N$ observations at $n_{sp}$ sites and $n_t$ time points. But, we typically do not have the resources to sample every site in every year. Additionally, we are often most interested in prediction of the abundance at unsampled sites in the most current year of the survey.

Let the subscript $s$ denote observations that were sampled (both past and present), and let the subscript $u$ denote observations that were unsampled. Let the subscript $c$ denote observations in the current year that we are interested in predicting, and let the subscript $p$ denote observations in the past that we are not interested in predicting. Finally, let the subscript $a$ denote all of the observations. Then we can partition $\mathbf{y}_a$ into 

$$
\mathbf{y}_a = [\mathbf{y}_{up}', \mathbf{y}_{sp}', \mathbf{y}_{uc}', \mathbf{y}_{sc}']'.
$$

so that $\mathbf{y}_{up}$ is the response vector at unsampled sites in the past, $\mathbf{y}_{sp}$ is the response vector at sampled sites in the past, $\mathbf{y}_{uc}$ is the response vector at unsampled sites in the current year, and $\mathbf{y}_{sc}$ is the response vector at sampled sites in the current year.

Our primary goal is to use the model developed in the previous section to predict values for $\mathbf{\tilde{y}}_{uc}$ from the observed data in $\mathbf{\tilde{y}}_{sp}$ and $\mathbf{\tilde{y}}_{sc}$, where $\mathbf{\tilde{y}_{uc}}$, $\mathbf{\tilde{y}}_{sp}$, and $\mathbf{\tilde{y}}_{sc}$ denote the realized values from the spatiotemporal process generating the response vector in the unsampled current sites, sampled past sites, and sampled current sites, respectively. 

We are commonly interested in predicting the total abundance for the most recent year in the set of surveys. That is, we want to find optimal weights $\mathbf{a}'$ to apply to the sampled data $\mathbf{a}' \mathbf{\tilde{y}}_s$, where  $\mathbf{\tilde{y}}_s \equiv [\mathbf{\tilde{y}}_{sp}', \mathbf{\tilde{y}}_{sc}']'$, such that $\mathbf{a}' \mathbf{y}_s$ is the Best Linear Unbiased Predictor (BLUP) for $\mathbf{b}_c' \mathbf{\tilde{y}}_c$. If we are interested in the total abundance in the current year, then $\mathbf{b}_c$ is a vector of 1's, $\mathbf{b}_p$ is a vector of 0's, and $\mathbf{b}_a = [\mathbf{b}_p', \mathbf{b}_c']'$, so that we are adding up all values of $\mathbf{y}_c$ for our predictor. 

Unbiasedness implies that $E(\mathbf{a'}\mathbf{y}_s) = E(\mathbf{b}_a'\mathbf{y}_a)$ for all $\bm{\beta}$. So, denoting $\mathbf{X}_s$ as the design matrix for sampled sites, $\mathbf{a'} \mathbf{X}_s \bm{\beta}$ = $\mathbf{b'} \mathbf{X} \bm{\beta}$ for every $\bm{\beta}$, implying that $\mathbf{a'} \mathbf{X}_s = \mathbf{b'}_a \mathbf{X}$.

The kriging weights are then found by finding $\bm{\lambda}$ such that

$$
E\{(\mathbf{a'}\mathbf{y}_s - \mathbf{b'}_a \mathbf{y}_a)(\mathbf{a'}\mathbf{y}_s - \mathbf{b'}_a \mathbf{z}_a)\} - E\{(\bm{\lambda'}\mathbf{y}_s - \mathbf{b'}_a \mathbf{z}_a)(\bm{\lambda}'\mathbf{y}_s - \mathbf{b'}_a \mathbf{z}_a)\}
$$

is greater than 0 for all $\mathbf{a'}$. The prediction equations are

$$
\begin{pmatrix}
\bm{\Sigma}_{s, s} & \mathbf{X}_s \\
\mathbf{X}_s' & 0
\end{pmatrix} 
\begin{pmatrix}
\bm{\lambda} \\
m
\end{pmatrix} = 
\begin{pmatrix}
\bm{\Sigma}_{s, s} & \bm{\Sigma}_{s, u} \\
\mathbf{X}_{s}' & \mathbf{X}_{u}'
\end{pmatrix} 
\begin{pmatrix}
\mathbf{b}_{s} \\
\mathbf{b}_{u}
\end{pmatrix},
$$

where again the subscripts $s$ and $u$ denote sampled and unsampled observations. For example, letting $n$ denote the number of sampled observations, $\bm{\Sigma}_{s, s}$ denotes the $n \times n$ submatrix of $\bm{\Sigma}$ corresponding only to rows and columns of sampled observations and $\bm{\Sigma}_{u, s}$ denotes the $(N - n) \times n$ submatrix of $\bm{\Sigma}$ corresponding to rows of observations that were not sampled and columns of observations that were sampled.

Then, $\bm{\lambda}$ is an $n \times 1$ vector. If we are interested in predicting the abundance in the most current year, the vector $\mathbf{b}_{s}$ is a vector of 1's and 0's, with 1's for the sampled sites in the current year and 0's for the sampled sites in the past years. The vector $\mathbf{b}_u$ is a also a vector of 1's and 0's, with 1's for the unsampled sites in the current year and 0's for the unsampled sites in the past years.

Then, we can solve for the prediction weights as

$$
\bm{\lambda}_s = \mathbf{b}_{s}' + \mathbf{b}_{u}' (\bm{\Sigma}_{u, s}\bm{\Sigma}_{s, s}^{-1}) - \mathbf{b}'_{u}(\bm{\Sigma}_{u, s} \bm{\Sigma}_{s, s}^{-1})\mathbf{X}_s(\mathbf{X}_s'\bm{\Sigma}_{s, s}^{-1}\mathbf{X}_s)^{-1}\mathbf{X}_s'\bm{\Sigma}_{s, s}^{-1} + \mathbf{b}_{u}' \mathbf{X}_{u}'(\mathbf{X}_s'\bm{\Sigma}_{s, s}^{-1}\mathbf{X}_s)^{-1}\mathbf{X}_s \bm{\Sigma}_{s, s}^{-1}.
$$

Our prediction for the total abundance in the current year of the survey is then

$$
\bm{\lambda}_s' \mathbf{\tilde{y}}_s,
$$

which is equivalent to 

$$
\mathbf{b}_{s}'\mathbf{\tilde{y}}_{s} + \mathbf{b}_{u}' \mathbf{\hat{y}}_{u},
$$

where $\mathbf{\hat{y}}_{u} = \bm{\Sigma}_{u, s} \Sigma_{s, s}^{-1} (\mathbf{\tilde{y}}_s - \bm{\hat{\mu}}_s) + \bm{\hat{\mu}}_u$ with $\bm{\hat{\mu}}_s = \mathbf{X}_s \bm{\hat{\beta}}_{GLS}, \bm{\hat{\mu}}_u = \mathbf{X}_u \bm{\hat{\beta}}_{GLS}$. $\bm{\hat{\beta}}_{GLS}$ is the generalized least squares estimator $(\mathbf{X}_s' \bm{\Sigma}_{s, s}^{-1} \mathbf{X}_s)^{-1} \mathbf{X}_s' \bm{\Sigma}_{s, s}^{-1} \mathbf{y}_s$.

The prediction has a prediction variance

$$
E((\bm{\lambda}_s'\mathbf{y}_s - \mathbf{b}_a'\mathbf{y}_a)(\bm{\lambda}_s'\mathbf{y}_s - \mathbf{b}_a'\mathbf{y}_a)) =
$$

$$
\bm{\lambda}_s'\bm{\Sigma}_{s, s}\bm{\lambda}_s - 2 \mathbf{b}_a' \bm{\Sigma}_{a ,s} \bm{\lambda}_s + \mathbf{b}_a' \bm{\Sigma}\mathbf{b}_a,
$$

Note that, again, if we are only interested in the total abundance in the current year, then unsampled sites in the past do not contribute to $\bm{\lambda}_s$ nor to the prediction variance because $\mathbf{b}_{up}$ is $\mathbf{0}$. Therefore, $\bm{\lambda}_s$ can be rewritten as

$$
\bm{\lambda}_s = \mathbf{b}_{s}' + \mathbf{b}_{uc}' (\bm{\Sigma}_{uc, s}\bm{\Sigma}_{s, s}^{-1}) - \mathbf{b}'_{uc}(\bm{\Sigma}_{uc, s} \bm{\Sigma}_{s, s}^{-1})\mathbf{X}_s(\mathbf{X}_s'\bm{\Sigma}_{s, s}^{-1}\mathbf{X}_s)^{-1}\mathbf{X}_s'\bm{\Sigma}_{s, s}^{-1} + \mathbf{b}_{uc}' \mathbf{X}_{uc}'(\mathbf{X}_s'\bm{\Sigma}_{s, s}^{-1}\mathbf{X}_s)^{-1}\mathbf{X}_s \bm{\Sigma}_{s, s}^{-1}.
$$

Additionally, sampled sites in the past do not contribute to the prediction variance in the second and third terms in the prediction variance because $\mathbf{b}_{sp}$ is $\mathbf{0}$. The prediction variance can then be rewritten as

$$
\bm{\lambda}_s'\bm{\Sigma}_{s, s}\bm{\lambda}_s - 2 \mathbf{b}_{c}' \bm{\Sigma}_{c, s} \bm{\lambda}_s + \mathbf{b}_{c}' \bm{\Sigma_{c, c}} \mathbf{b}_{c},
$$


Finally, our site-by-site predictions for the unsampled sites in both the past and the present come from the usual block kriging formulae:

$$
\mathbf{\hat{y}}_{u} = \bm{\Sigma}_{u, s} \bm{\Sigma}_{s, s}^{-1}(\mathbf{y}_s - \bm{\hat{\mu}}_s) + \bm{\hat{\mu}}_{u},
$$





