#!/bin/bash
#SBATCH --job-name=higham_test    # Job name
#SBATCH --mail-type=END,FAIL          # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=mhigham@stlawu.edu  # Where to send mail	
#SBATCH --ntasks=1                    # Run on a single CPU
#SBATCH --mem=70gb                     # Job memory request
#SBATCH --time=01-03:45:00               # Time limit days-hrs:min:sec
#SBATCH --output=slurm_%j.log   # Standard output and error log


echo "Date              = $(date)"
echo "Hostname          = $(hostname -s)"
echo "Working Directory = $(pwd)"
echo ""
echo "Number of Nodes Allocated      = $SLURM_JOB_NUM_NODES"
echo "Number of Tasks Allocated      = $SLURM_NTASKS"
echo "Number of Cores/Task Allocated = $SLURM_CPUS_PER_TASK"

#module load R/3.6.3
module load R/4.0.0

# Rscript /home/mhigham/test_hpc.R 
Rscript /home/mhigham/FPSpatioTemp/inst/simulation_script.R 

echo -n "Finished program at: "
date
echo ""
